//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Template {
    
    private TemplateTemplateConfiguration[] templateConfigurationField;
    
    private TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespace[][][][][] templateFilesField;
    
    private string originatorField;
    
    private string createdField;
    
    private string lastModifiedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TemplateConfiguration", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TemplateTemplateConfiguration[] TemplateConfiguration {
        get {
            return this.templateConfigurationField;
        }
        set {
            this.templateConfigurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CodeDomFile", typeof(TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespace[][][]), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CompileUnit", typeof(TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespace[][]), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, NestingLevel=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Namespaces", typeof(TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespace[]), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, NestingLevel=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Namespace", typeof(TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespace), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, NestingLevel=3)]
    public TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespace[][][][][] TemplateFiles {
        get {
            return this.templateFilesField;
        }
        set {
            this.templateFilesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string originator {
        get {
            return this.originatorField;
        }
        set {
            this.originatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string created {
        get {
            return this.createdField;
        }
        set {
            this.createdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lastModified {
        get {
            return this.lastModifiedField;
        }
        set {
            this.lastModifiedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TemplateTemplateConfiguration {
    
    private string _NameField;
    
    private string iconField;
    
    private string _CategoryField;
    
    private string languageNameField;
    
    private string projectTypeField;
    
    private string _DescriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string _Name {
        get {
            return this._NameField;
        }
        set {
            this._NameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string _Category {
        get {
            return this._CategoryField;
        }
        set {
            this._CategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LanguageName {
        get {
            return this.languageNameField;
        }
        set {
            this.languageNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProjectType {
        get {
            return this.projectTypeField;
        }
        set {
            this.projectTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string _Description {
        get {
            return this._DescriptionField;
        }
        set {
            this._DescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespace {
    
    private TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespaceTypesTypeDeclaration[][] typesField;
    
    private TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespaceImportsNamespaceImport[][] importsField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("TypeDeclaration", typeof(TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespaceTypesTypeDeclaration), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespaceTypesTypeDeclaration[][] Types {
        get {
            return this.typesField;
        }
        set {
            this.typesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("NamespaceImport", typeof(TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespaceImportsNamespaceImport), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespaceImportsNamespaceImport[][] Imports {
        get {
            return this.importsField;
        }
        set {
            this.importsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespaceTypesTypeDeclaration {
    
    private string membersField;
    
    private TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespaceTypesTypeDeclarationBaseTypesTypeReference[][] baseTypesField;
    
    private string nameField;
    
    private string isClassField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Members {
        get {
            return this.membersField;
        }
        set {
            this.membersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("TypeReference", typeof(TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespaceTypesTypeDeclarationBaseTypesTypeReference), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespaceTypesTypeDeclarationBaseTypesTypeReference[][] BaseTypes {
        get {
            return this.baseTypesField;
        }
        set {
            this.baseTypesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IsClass {
        get {
            return this.isClassField;
        }
        set {
            this.isClassField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespaceTypesTypeDeclarationBaseTypesTypeReference {
    
    private string baseTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BaseType {
        get {
            return this.baseTypeField;
        }
        set {
            this.baseTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TemplateTemplateFilesCodeDomFileCompileUnitNamespacesNamespaceImportsNamespaceImport {
    
    private string namespaceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Namespace {
        get {
            return this.namespaceField;
        }
        set {
            this.namespaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private Template[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Template")]
    public Template[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
