//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace HolisticWare.IDE.AutomationTools.Snippets.VisualStudio {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet", IsNullable=false)]
    public partial class CodeSnippets {
        
        private CodeSnippet[] codeSnippetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CodeSnippet")]
        public CodeSnippet[] CodeSnippet {
            get {
                return this.codeSnippetField;
            }
            set {
                this.codeSnippetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet", IsNullable=false)]
    public partial class CodeSnippet {
        
        private CodeSnippetHeader headerField;
        
        private object[] snippetField;
        
        private string formatField;
        
        /// <remarks/>
        public CodeSnippetHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Code", typeof(CodeSnippetCode), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Declarations", typeof(CodeSnippetDeclarations), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Imports", typeof(CodeSnippetImports), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("References", typeof(CodeSnippetReferences), IsNullable=false)]
        public object[] Snippet {
            get {
                return this.snippetField;
            }
            set {
                this.snippetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet")]
    public partial class CodeSnippetHeader {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Author", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Description", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("HelpUrl", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Keywords", typeof(CodeSnippetKeywords))]
        [System.Xml.Serialization.XmlElementAttribute("Shortcut", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("SnippetTypes", typeof(CodeSnippetSnippetTypes))]
        [System.Xml.Serialization.XmlElementAttribute("Title", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet")]
    public partial class CodeSnippetKeywords {
        
        private string[] keywordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Keyword")]
        public string[] Keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet")]
    public partial class CodeSnippetSnippetTypes {
        
        private string[] snippetTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SnippetType")]
        public string[] SnippetType {
            get {
                return this.snippetTypeField;
            }
            set {
                this.snippetTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        Author,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        HelpUrl,
        
        /// <remarks/>
        Keywords,
        
        /// <remarks/>
        Shortcut,
        
        /// <remarks/>
        SnippetTypes,
        
        /// <remarks/>
        Title,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet")]
    public partial class CodeSnippetCode {
        
        private string languageField;
        
        private string kindField;
        
        private string delimiterField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet")]
    public partial class CodeSnippetDeclarations {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Literal", typeof(CodeSnippetDeclarationsLiteral))]
        [System.Xml.Serialization.XmlElementAttribute("Object", typeof(CodeSnippetDeclarationsObject))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet")]
    public partial class CodeSnippetDeclarationsLiteral {
        
        private string[] itemsField;
        
        private ItemsChoiceType2[] itemsElementNameField;
        
        private bool editableField;
        
        private bool editableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Default", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Function", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ID", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ToolTip", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Type", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType2[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Editable {
            get {
                return this.editableField;
            }
            set {
                this.editableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EditableSpecified {
            get {
                return this.editableFieldSpecified;
            }
            set {
                this.editableFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet", IncludeInSchema=false)]
    public enum ItemsChoiceType2 {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Function,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        ToolTip,
        
        /// <remarks/>
        Type,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet")]
    public partial class CodeSnippetDeclarationsObject {
        
        private string[] itemsField;
        
        private ItemsChoiceType3[] itemsElementNameField;
        
        private bool editableField;
        
        private bool editableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Default", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Function", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ID", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ToolTip", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Type", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType3[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Editable {
            get {
                return this.editableField;
            }
            set {
                this.editableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EditableSpecified {
            get {
                return this.editableFieldSpecified;
            }
            set {
                this.editableFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet", IncludeInSchema=false)]
    public enum ItemsChoiceType3 {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Function,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        ToolTip,
        
        /// <remarks/>
        Type,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet")]
    public partial class CodeSnippetImports {
        
        private CodeSnippetImportsImport[] importField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Import")]
        public CodeSnippetImportsImport[] Import {
            get {
                return this.importField;
            }
            set {
                this.importField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet")]
    public partial class CodeSnippetImportsImport {
        
        private string namespaceField;
        
        /// <remarks/>
        public string Namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet")]
    public partial class CodeSnippetReferences {
        
        private CodeSnippetReferencesReference[] referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public CodeSnippetReferencesReference[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet")]
    public partial class CodeSnippetReferencesReference {
        
        private string[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Assembly", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Url", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        Assembly,
        
        /// <remarks/>
        Url,
    }
}
